# Softmax & Retarded Neural Network

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Two layer Neural Network

In [17]:
def sigmoid(z):
    return 1./(1-np.exp(-z))

In [28]:

class TLNN:
    
    __network = {}
    
    def __init__(self,input_size,output_size,layer_size):
        
        #first layer
        self.__network['W1'] = np.random.uniform(0,1,(input_size,layer_size))
        self.__network['b1'] = np.random.uniform(0,1,(layer_size))
        
        #second layer
        self.__network['W2'] = np.random.uniform(0,1,(layer_size,output_size))
        self.__network['b2'] = np.random.uniform(0,1,(output_size))
        
    def forward(self,x):
        W1,W2 = self.__network['W1'], self.__network['W2']
        b1,b2 = self.__network['b1'], self.__network['b2']
        
        a1 = np.matmul(x,W1) + b1.T #evaluation
        f1 = sigmoid(a1) #activation function
        
        a2 = np.matmul(f1.T,W2) + b2
        f2 = sigmoid(a2)
        
        y = f2 #identity function
        
        return y

In [56]:
MyNN = TwoLayerNN(2,1,2)
x = np.array([6,7])
target = np.array([2,3,5])

In [57]:
MyNN.forward(x)

array([1.])

### Softmax

In [58]:
def softmax(a):
    
    supp = np.max(a)
    
    return np.exp(a-supp)/np.sum(np.exp(a-supp))

In [59]:
softmax(x)

array([0.26894142, 0.73105858])

In [60]:
np.sum(softmax(x))

1.0

In [61]:

class TLNNsft:
    
    __network = {}
    
    def __init__(self,input_size,output_size,layer_size):
        
        #first layer
        self.__network['W1'] = np.random.uniform(0,1,(input_size,layer_size))
        self.__network['b1'] = np.zeros(layer_size)
        
        #second layer
        self.__network['W2'] = np.random.uniform(0,1,(layer_size,output_size))
        self.__network['b2'] = np.zeros(output_size)
        
    def forward(self,x):
        W1,W2 = self.__network['W1'], self.__network['W2']
        b1,b2 = self.__network['b1'], self.__network['b2']
        
        a1 = np.matmul(x,W1) + b1.T #evaluation
        f1 = sigmoid(a1) #activation function
        
        a2 = np.matmul(f1.T,W2) + b2
        f2 = sigmoid(a2)
        
        y = softmax(f2) #identity function
        
        return y
    
    def error(self,x,t):
        '''
        Cross entropy loss
        t : target
        x : input
        '''
        y = self.forward(x)
        E = -(np.matmul(t,np.log(y).T)+np.matmul((1-t),(1-np.log(y)).T))/len(t)
        return E
    
    def accuracy(self,x,t):
        y = self.forward(x)
        return np.sum(y==t)/len(t)
    
    def train(self,x,t):
        y = self.forward()
    
    

In [62]:
MyNN = TLNNsft(2,3,2)

In [63]:
MyNN.forward(x)

array([9.94799703e-01, 4.48371442e-03, 7.16582502e-04])

In [64]:
MyNN.error(x,target)

33.07377115747093

In [65]:
MyNN.accuracy(x,target)

0.0