In [12]:
import numpy as np

a = np.random.randn(5,6)
print(a)
print()
b = a.reshape(3,10)
print(b)
print()
c = np.array([[1,2],[1,1]])
print(c)
e = np.array([1,2])
print(e)
f = np.dot(c,e.T)
print(f)

fa = np.append(fd,fd)
fd = np.array([[1.]])
print(fa)

[[-0.79452025 -1.00307499  0.62396603 -0.25162424 -0.8154978  -0.62426362]
 [ 0.72019726 -0.05966956 -0.06130791 -1.13500871  1.66659059 -0.33626347]
 [ 0.88853272  0.85406825 -0.64088932  1.378114    1.91078182  1.67156857]
 [-1.56608169 -0.85729015 -0.10686482 -0.71898471  0.47054376 -0.24662623]
 [ 1.30444638 -0.19840947  1.55746377  0.43630195  0.13795713  0.60585692]]

[[-0.79452025 -1.00307499  0.62396603 -0.25162424 -0.8154978  -0.62426362
   0.72019726 -0.05966956 -0.06130791 -1.13500871]
 [ 1.66659059 -0.33626347  0.88853272  0.85406825 -0.64088932  1.378114
   1.91078182  1.67156857 -1.56608169 -0.85729015]
 [-0.10686482 -0.71898471  0.47054376 -0.24662623  1.30444638 -0.19840947
   1.55746377  0.43630195  0.13795713  0.60585692]]

[[1 2]
 [1 1]]
[1 2]
[5 3]
[1. 1.]


In [20]:
import numpy as np



data1 = np.array([10**(-4+i/100) for i in range(801)]) # 저장하는 데이터 10^-4~10^4
temp = []
for i in range(801):
    for j in range(i,801):
        temp.append([data1[i],data1[j],data1[i]+data1[j],data1[i]*data1[j]])

data2 = np.array(temp)
print(data2)

#np.save('my_data.npy', data2) # numpy.ndarray 저장. @파일명, @값



#data3 = np.load('my_data.npy') # 데이터 로드. @파일명

[[1.00000000e-04 1.00000000e-04 2.00000000e-04 1.00000000e-08]
 [1.00000000e-04 1.02329299e-04 2.02329299e-04 1.02329299e-08]
 [1.00000000e-04 1.04712855e-04 2.04712855e-04 1.04712855e-08]
 ...
 [9.77237221e+03 9.77237221e+03 1.95447444e+04 9.54992586e+07]
 [9.77237221e+03 1.00000000e+04 1.97723722e+04 9.77237221e+07]
 [1.00000000e+04 1.00000000e+04 2.00000000e+04 1.00000000e+08]]
